### ISSUE TITLE
Cannot find core configuration file.

### ISSUE THREAD

**Issue by Olddies710** [bogdasari4/MyOpenMuWeb#1]
I got this error after command composer install, i have edited postgres password 

Cannot find core configuration file.

**Comment by bogdasari4** [comment]
> I got this error after command composer install, i have edited postgres password
> 
> Cannot find core configuration file.

You are missing the `core.json` file in the `\App\Json\Config\` directory. Create this file, 
```JSON
{
    "LANGUAGE": {
        "CODE": {
            "570": {
                "ISO": "rus"
            },
            "45": {
                "ISO": "eng"
            }
        },
        "SET": 570,
        "EXPIRES": 2419200
    },
    "DEFAULT": {
        "TIMEZONE": "Europe/Moscow",
        "DATABASE": "postgresql",
        "PAGE": "main",
        "TEMPLATE": "openmu",
        "CACHE": {
            "LIFETIME": 900
        }
    }
}
```
or use the latest git image.
